# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-18 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('content', models.TextField(verbose_name='file')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='start date')),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='update time')),
            ],
        ),
    ]
